# Generated by Django 5.0.3 on 2024-04-04 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction_listings_bids_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listings',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bids',
            name='listingid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bidsreceived', to='auctions.auction_listings'),
        ),
        migrations.AlterField(
            model_name='bids',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bidsmade', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comments',
            name='listingid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentsposted', to='auctions.auction_listings'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentsmade', to=settings.AUTH_USER_MODEL),
        ),
    ]
