# Generated by Django 5.0.2 on 2024-04-19 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_auction_listings_title_alter_bids_bidprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_listings',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
