# Generated by Django 5.0.2 on 2024-04-25 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_auction_listings_startingprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_listings',
            name='finalPrice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
